# coding: utf-8
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

use_frameworks!
target 'AEPSampleApp' do
  pod 'AEPCore'
  pod 'AEPLifecycle'
  pod 'AEPIdentity'
  pod 'AEPSignal'
  pod 'AEPUserProfile'
  pod 'AEPEdge'
  pod 'AEPEdgeConsent'
  pod 'AEPEdgeIdentity'
  pod 'AEPAssurance'
  pod 'AEPMessaging'
  pod 'AEPOptimize'
end
