source 'https://github.com/CocoaPods/Specs.git’
platform :ios, '10.0'

use_frameworks!
target 'AEPSampleAppObjC' do
	pod 'AEPServices'
	pod 'AEPCore'
	pod 'AEPLifecycle'
	pod 'AEPIdentity'
	pod 'AEPSignal'
	pod 'AEPRulesEngine'
end
