# coding: utf-8
source 'https://github.com/CocoaPods/Specs.git’
platform :ios, '10.0'

use_frameworks!
target 'AEPSampleAppObjC' do

  pod 'AEPServices'
  pod 'AEPCore'
  pod 'AEPLifecycle'
  pod 'AEPIdentity'
  pod 'AEPSignal'
  pod 'AEPRulesEngine'
  pod 'AEPAssurance'

  pod 'AEPMessaging', :git => 'https://github.com/adobe/aepsdk-messaging-ios.git', :branch => 'staging'
  pod 'AEPOptimize', :git => 'https://github.com/adobe/aepsdk-optimize-ios.git', :branch => 'staging'

end
